### ISSUE TITLE
is kisscartoon broken?

### ISSUE THREAD

**Issue by toddfraser88** [Twoure/KissNetwork.bundle#30]
I'm just wondering if kisscartoon is broken at the moment? or if it's just me?

**Comment by Twoure** [comment]
Working on my end.

Please include logs as an attachment, so I can see the issue.
Need `com.plexapp.plugins.kissnetwork.log` and `com.plexapp.system.log`.  Log file location info can be found [here](https://github.com/Twoure/KissNetwork.bundle/wiki/Log%20files).

Also for future reference, please review the [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue) wiki section before create a new issue.

**Comment by toddfraser88** [comment]
OK, I hope this works

[com.plexapp.plugins.kissnetwork.log.1.txt](https://github.com/Twoure/KissNetwork.bundle/files/441362/com.plexapp.plugins.kissnetwork.log.1.txt)
[com.plexapp.plugins.kissnetwork.log.txt](https://github.com/Twoure/KissNetwork.bundle/files/441364/com.plexapp.plugins.kissnetwork.log.txt)
[com.plexapp.system.log.txt](https://github.com/Twoure/KissNetwork.bundle/files/441363/com.plexapp.system.log.txt)

**Comment by Twoure** [comment]
Try clearing the `DataHTTP` directory located within `Data/com.plexapp.plugins.kissnetwork/DataItems/DataHTTP/`.  See Data directory location info [here](https://github.com/Twoure/KissNetwork.bundle/wiki/Data%20files).

Alternatively, you can use the [Cache Tools](https://github.com/Twoure/KissNetwork.bundle/wiki/Developer%20Tools#cache-tools) located within the channel's [DeveloperTools](https://github.com/Twoure/KissNetwork.bundle/wiki/Developer%20Tools) _(enable developer tools within channel preferences to see the menu within "About / Help" section)_.

After clearing the cached http pages (as described above), make sure to exit channel then re-enter.  Then retry playing the same video within the channel.

Let me know how it goes.

**Comment by toddfraser88** [comment]
I noticed something 
enable developer tools - would not change to true, kept giving me an error - even as root

I deleted /DataHTTP/ manually and tried again, no change

[com.plexapp.plugins.kissnetwork.log.2.txt](https://github.com/Twoure/KissNetwork.bundle/files/441404/com.plexapp.plugins.kissnetwork.log.2.txt)
[com.plexapp.system.log.5.txt](https://github.com/Twoure/KissNetwork.bundle/files/441403/com.plexapp.system.log.5.txt)

**Comment by Twoure** [comment]
Note, log files 1-5 are setup with `.log` being the current file, `.log.1` the most recent old file, and so-on-and-so-forth.  With 5 being the oldest.  Files start over if PMS restarts, plugin restarts, or log file reaches a size limit.  If the files included are correct by their numbers, then these are old logs and do not show me the current state of your plugin.

Regardless, the system log you sent this time is saying:

```
IOError: [Errno 2] No such file or directory: '/media/5aed1210-a7b4-4fc4-9520-1253e1bf327c/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/KissNetwork.bundle/Contents/Info.plist'
```

Which means the file is missing, corrupt, or wasn't available while the system bundle was initializing.  If it does exists and Plex has proper permissions to access the file, then a simple PMS restart should remedy this issue.

However, I did note from your logs that I have a bug for new installs, and fixed it within my [dev](https://github.com/Twoure/KissNetwork.bundle/tree/dev) branch.  Please download and try the `dev` branch ([dev zip _07d4d28_](https://github.com/Twoure/KissNetwork.bundle/archive/07d4d289004554ff3826f52d53406c7005a9bf47.zip)).

Also note for Unix based platforms, you will need to `chown plex:plex -R` for the _KissNetwork.bundle_ after moving it into the Plug-ins directory.

> enable developer tools - would not change to true, kept giving me an error - even as root

Does the following file exist?

```
plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/Plug-in\ Support/Preferences/com.plexapp.plugins.kissnetwork.xml
```

If not then there may be a permissions error with how your PMS server is setup.

**Comment by toddfraser88** [comment]
Sorry, I thought the logs with the highest number were the most recent, my bad

I think chown plex:plex -R you suggested did the trick - Steven Universe will play now, so thanks very much!

Though I've noticed that enable developer tools still will not change to true when I click it, I'd like some help to fix that, if at all possible

[com.plexapp.plugins.kissnetwork.log.txt](https://github.com/Twoure/KissNetwork.bundle/files/441735/com.plexapp.plugins.kissnetwork.log.txt)
[com.plexapp.system.log.txt](https://github.com/Twoure/KissNetwork.bundle/files/441736/com.plexapp.system.log.txt)

**Comment by Twoure** [comment]
> I think chown plex:plex -R you suggested did the trick - Steven Universe will play now, so thanks very much!

Glad it fixed that part of the issue.

> Though I've noticed that enable developer tools still will not change to true when I click it, I'd like some help to fix that, if at all possible

This is concerning, considering the directory the channel preferences are created and saved within is supposed to be owned and maintained by the default user `plex`.  Not sure, but seems like your server does not have permissions to the preferences file.

Open an terminal and navigate to the following directory:

```
/media/5aed1210-a7b4-4fc4-9520-1253e1bf327c/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Preferences
```

then do `ls -alh` to display the current `user:group` permissions.  It should be `plex:plex` by default.  If not then this is the issue.  **Note:** as before the `com.plexapp.plugins.kissnetwork.xml` file within the `Preferences` folder is where PMS stores the users preferences for this channel.  You can manually edit the file, but make sure after editing that is is still owned by `plex` (i.e. `chown plex:plex com.plexapp.plugins.kissnetwork.xml`).  Also after manually editing, you'll have to restart your PMS to see the changes, since you can't save changes from the normal client interface.

Did you try changing the channel's preferences from different clients?  Might be a client issue, but doubtful.

The log files don't show anything unusual, so my hunch is its either a file/folder permissions error, client issue, or there is some internal error within how your server is setup.

**Comment by toddfraser88** [comment]
ok

ls -alh
total 28K
drwxr-xr-x 2 plex plex 4.0K Aug 29 04:34 .
drwxr-xr-x 7 plex plex 4.0K Jan 17  2016 ..
-rw-rw-rw- 1 plex plex  102 Jan 17  2016 com.plexapp.agents.localmedia.xml
-rw-rw-rw- 1 plex plex  153 Mar 24 01:43 com.plexapp.agents.opensubtitles.xml
-rw-r--r-- 1 plex plex  139 Jul  7 08:03 com.plexapp.agents.thetvdb.xml
-rw-r--r-- 1 plex plex  541 Aug 29 04:34 com.plexapp.plugins.kissnetwork.xml
-rw-r--r-- 1 plex plex  121 Jan 17  2016 com.plexapp.system.xml

permissions seem fine,
I'll try a different client

**Comment by toddfraser88** [comment]
I tried out the plex media player for windows, but I couldn't find where channel preferences were to enable developer tools
I'm sure it's somewhere, I'm just not seeing it

**Comment by Twoure** [comment]
Since you had to `chown` the Kiss bundle, it may be that the preference file wasn't created properly the first time around.  Try the following: shutdown your PMS, then delete the `/media/5aed1210-a7b4-4fc4-9520-1253e1bf327c/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Preferences/com.plexapp.plugins.kissnetwork.xml` file.  Then start PMS, open the Plex Web client, and try to change a setting within this channel's preferences.

If the above doesn't work, then you can try a different web browser.

If preferences are still causing issues, then it may be worth testing an official channel with preferences.  The PBS, SoundCloud, and Vimeo channels all have channel preferences and come from the official channel directory.  There may be others, this is only what I could recall at the moment.

**Comment by toddfraser88** [comment]
Thanks,
after deleting that file, I can change settings in the web browser client now,
on my main client, PlexXBMC, it's still broken though, so I gather it's a problem with PlexXBMC and not kissnetwork

**Comment by Twoure** [comment]
If PlexXBMC fails on the other official channels that also include preferences, then yes this is an issue with PlexXBMC and not my channel.

**Comment by blackgold73** [comment]
Every time I try to watch anything in Cartoons, I get the error, Sorry there was a problem playing this item. 

[PMSLogs_20160831-193216.zip](https://github.com/Twoure/KissNetwork.bundle/files/448477/PMSLogs_20160831-193216.zip)

**Comment by Twoure** [comment]
Changed how the preferences are handled in [v1.2.7](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.7), but not sure will make a difference within your PlexXBMC client.

**Comment by blackgold73** [comment]
Thank you

**Comment by blackgold73** [comment]
Still getting Sorry, can't play this item. But I can read, I just can't
watch anything. Thank you for all your help

**Comment by blackgold73** [comment]
Never mind, It was just some of the videos

**Comment by Twoure** [comment]
Main issue resolved.
