### ISSUE TITLE
today started getting no items in list on all channels for kiss

### ISSUE THREAD

**Issue by jimf54** [Twoure/KissNetwork.bundle#38]
today started getting no items in list on all channels for kiss

**Comment by jimf54** [comment]
ok just noticed cannot conect to the website in browser
This site can’t be reached

kisscartoon.me’s server DNS address could not be found.

**Comment by Twoure** [comment]
Yes, seems most of the kiss sites are down for the day.  Nothing to be done but wait and see if they come back.  Sorry.

**Comment by Atchuu** [comment]
It appears that they switched the domains again...

You'll need to update this:
_(link removed by mod)_

KissAnime is now http://kissanime.io/
I don't know about the others...

**Comment by Twoure** [comment]
Please refer to https://github.com/Twoure/KissNetwork.bundle/issues/36#issuecomment-266129131

**Comment by deeelwy** [comment]
Been down for 3 or 4 days now. Wonder if it'll come back up.

Is porting this Plex Channel to a different anime/manga/cartoon/etc site doable?

Hoping to jynx Kiss into coming back to life.

**Comment by Twoure** [comment]
Kissasian, Ksscartoon, and Read Comics Online, all say they are fixing the issue and hope to have the sites up "soon,"

https://www.facebook.com/kissasianweb/posts/1399546460065325
https://www.facebook.com/kisscartoonweb/posts/899696140166106
https://www.facebook.com/readcomiconlineweb/posts/1550128478332134

Kissanime facebook page is normally quite anymore, because last time it drew too much attention and was removed, but I would assume it follows the same comment as the above posted.

**Comment by monolyth421** [comment]
kissanime.io is a copycat

http://kissanime.ru/ is the correct URL

**Comment by Twoure** [comment]
All sites are back online, and I've pushed [v1.2.8](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.2.8) with various fixes.

Refer to [(KissAnime admin) This is what happen to Kiss sites in the last two weeks](https://www.reddit.com/r/KissAnime/comments/5iy7oy/kissanime_admin_this_is_what_happen_to_kiss_sites/) for more info on the `.io` site.

If you have further issues after updating to `v1.2.8`, then please refer to [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue).
