### ISSUE TITLE
new style kissasian subtitles are currently not supported by this plugin

### ISSUE THREAD

**Issue by ginobean** [Twoure/KissNetwork.bundle#41]
It looks like Kissasian is adding subtitles as a separate element. Here's an example: http://kissasian.com/Drama/Father-I-ll-Take-Care-of-You/Episode-17?id=32061

As you can see, there are now subtitle controls, where you can select either 'English' or 'subtitles off' (click on the bubble icon in lower right corner of screen). 

Viewing the source, it looks like there's now a <track kind="subtitles" .. element that now contains the subtitles. 

As it stands now, these new style subtitles cannot be viewed using this Kissasian plugin.

**Comment by Twoure** [comment]
Correct, but this is not entirely new.  KissAsian has done this in the past as well.

Unfortunately, the Plex Channel Framework does not support subtitles in any capacity.  However, I have heard the Plex developers are looking into supporting subtitles in channels but there is currently no ETA on supported functionality.

If, and when, subtitles are supported in Channels, I'll update this channel to utilize them.  Otherwise for now, there is nothing I can do.  Sorry.

**Note:** Local media on your Plex Media Server does support subtitles.  Channels do not.

**Comment by ginobean** [comment]
Thanks for the explanation!

BTW, I just re-checked the link I had posted to this thread and it looks like the subtitles have been integrated into the video. They must have some kind of overnight process that incorporates the subtitles into the actual video stream..  So the subtitles, for the link I posted, DO show up now.
