### ISSUE TITLE
Folders Are Empty

### ISSUE THREAD

**Issue by mchawi** [Twoure/KissNetwork.bundle#47]
I got an error when trying to play videos, when I went on plex on my computer every folder was empty... I reinstalled it but it is still empty

**Comment by Twoure** [comment]
Look over [FAQ Installation: Why isn't this plugin visible under "Channels" on my server?](https://github.com/Twoure/KissNetwork.bundle/wiki/FAQ---Installation#1-why-isnt-this-channel-visible-under-channels-on-my-server).

If issue persist, then please review [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue), then add the appropriate logs/info to your original post.

**Comment by mchawi** [comment]
Cool! I got the anime to show, but now it says "There was a problem playing this item" on my computer and "Video Unavailable on my Roku"

PS: Thanks For The Reply, This is Awesome and Appreciate Your Hard Work :)

**Comment by Twoure** [comment]
Not sure if part of your current issue, but is seems the default video host is down, as they are [telling users](https://www.facebook.com/kissanimefp/posts/1399446826734294) to use the Openload streams for now.  However, currently the Openload code within `v1.2.8` is outdated and does not work.  You'll need to switch this channel's [Update Channel](https://github.com/Twoure/KissNetwork.bundle#update-channel) to `Development` to get the latest Openload code.

**Comment by mchawi** [comment]
Is that all i need to do? Will I need to go and get the code, or will it automatically get if for me? If I don't need to get it that does not seem to  be the problem. How did you find out that the video host is down, is there a website? Also, just to check I played a tv show on the cbs app and it did work. Also I have deleted and reinstalled kissnetwork. I have restarted pms and my com.

**Comment by Twoure** [comment]
> Is that all i need to do? Will I need to go and get the code, or will it automatically get if for me?

An update will appear within the channel, select it to apply.  Sometimes you may have to do it twice for update to register correctly.  Otherwise you can [download](https://github.com/Twoure/KissNetwork.bundle/archive/dev.zip) and install the `dev` branch [manually](https://github.com/Twoure/KissNetwork.bundle#install).

> How did you find out that the video host is down, is there a website?

Each kiss site has an official facebook page.  There is also a forum for the kiss sites.  I monitor both along with [/r/KissAnime](https://www.reddit.com/r/KissAnime/) to stay in the loop.  Refer to [KissCommunity Links](https://www.reddit.com/r/KissAnime/comments/5ju40r/kisscommunity_links/) and [KissCommunity Forum](http://forum.kissanime.com/index.php) for more info.

**Comment by Twoure** [comment]
@mchawi, working ok now?

**Comment by mchawi** [comment]
Yes, sorry for not saying sooner. Thanks for your help. Keep up the good work!
