### ISSUE TITLE
[Feature Request] Ability To Select Or Force Quality?

### ISSUE THREAD

**Issue by NicholasLAranda** [Twoure/KissNetwork.bundle#57]
I have a 55" 4k Samsung UHD Smart TV and it likes to play 720p over 1080p links, on an episode in KissCartoon that's verified to have a 1080p link, from KissAnime servers.

Is there any way to add a preferences to force 1080p / highest quality possible?

If yes, might as well add a quality selector for those who are burdened with lesser internet speeds.

**Comment by Twoure** [comment]
There already is a quality selection implemented within the channel, and uses the standard method that Plex Clients support.

However, each client handles stream quality selection differently.  For instance, my Android has a drop down menu that allows me to select the quality when I go to play a video.  Plex Web Client has a similar 3 dot menu that allows for quality selection at the time the video is selected to play.  **Edit:** Both of these clients also have a global client setting for channel/online quality and will honer that preference by default unless I manually choose the quality.  BUT, if my global default quality is 720p and I manually select a 1080p stream, then the server will transcode the 1080p stream down to 720p, because the global setting trumps the local _(weird but true)_. 

As for the Samsung TV Plex Clients, you'll have to set the global option in the Clients settings for a setting either called "Channel Quality" or "Online Quality".  Whatever that quality is set to, this channel will try and return the highest available stream to match the clients preference.

Refer to [Smart TVs (LG, 2016 Samsung, Sony, TiVo, Toshiba, VIZIO)](https://forums.plex.tv/categories/plex-for-smart-tvs-non-samsung) or [Samsung Smart Hub (2010-2015 models)](https://forums.plex.tv/categories/samsung-smart-hub) thread, depending on your model, to learn more about Samsung TV global Plex Client settings.
