### ISSUE TITLE
Latest update broke everything

### ISSUE THREAD

**Issue by ghost** [Twoure/KissNetwork.bundle#7]
I just downloaded the new version and now all videos say "not responding kiss cartoon is working to fix it" . any suggestions?

**Comment by Twoure** [comment]
That is appearing because the episode has no source video links.  The kiss sites remove dead links and don't always replace them with new ones right away.

That being said, can you play the episodes from a normal browser?  If so then try restarting Plex Media Server (PMS) and check if the channel give the same error.

Beyond that, I will need your logs.  Info for required logs and location can be found [here](https://forums.plex.tv/discussion/186988/rel-kissnetwork/p6#Comment_1084965).

**Comment by Twoure** [comment]
@rainman20 Thanks for the heads up.  Took some time and looked into what was going on.  The kiss sites are moving to hosting videos to OneDrive.  I have yet to correctly parse OneDrive videos for PMS.

I fixed your error above, so now it returns if it is the new OneDrive videos.  Try [v1.1.1](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.1.1) and get back with me.

**Comment by Twoure** [comment]
@rainman20 

[v1.1.2](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.1.2) now available.  Follow the update info in the [release post](https://forums.plex.tv/discussion/comment/1142987/#Comment_1142987).
[v1.1.2](https://github.com/Twoure/KissNetwork.bundle/releases/tag/v1.1.2) now supports OneDrive and OpenLoad videos.

Also note, from the release post, that the Kiss sites are currently undergoing a host change.  Many videos will be broken until they re-upload them to either OneDrive or OpenLoad.  This is the main reason behind the issue you posted.

**Comment by Twoure** [comment]
@rainman20 

Please let me know if the [latest](https://github.com/Twoure/KissNetwork.bundle/releases) release fixes your issue.

**Comment by ghost** [comment]
@Twoure yes, just updated and everything works. thanks

**Comment by Twoure** [comment]
Glad to hear, and thanks for the update.
